g0v/summit2018

- README.md
* html -> pug
* 截圖解釋開 branch 送 PR
> 💬 更新 README.md 的翻譯說明

- src/pages/LandingPage.vue
edited "about g0v", "about g0v summit" & "past events"
> `:speech_balloon: update en landing page`

- .gitignore
- package.json
- pull_airtable.sh
reopen PR from branch in origin repo
close #33
> 👷Pull Airtable data before build

- .travis.yml
參考：https://github.com/travis-ci/travis-ci/issues/9312
> 💚暫時修復 Travis CI GitHub Page 問題

- src/views/SponsorSection.vue
> 💄Use single image size for sponsor logo

- src/pages/LandingPage.vue
> 💄Full width flickr section

- src/pages/LandingPage.vue
- src/vue-awesome.js
> 💬更新 timeline 項目

- src/pages/LandingPage.vue
> 💬Update wording for timeline

- src/pages/LandingPage.vue
> 💬Add CTA button and link in timeline for CFP

- src/components/HeroImageMobile.vue
Taipei is more meaningful than the building name for international participants
> change location to Taipei

- src/components/CtaButton.vue
- src/pages/LandingPage.vue
- src/views/TheFooter.vue
- src/vue-awesome.js
close #77 
@besscsl 贊助大話的我先用第一個 email 囉，如果有要改再說~
> Add email links and make button round

- src/components/UnderlineLink.vue
- src/styles/_settings.scss
- src/views/NavBar.vue
- src/views/TheTimeline.vue
https://projects.invisionapp.com/d/main#/console/14716752/308282540/inspect
> 修改 Nav Bar 為淺色調

- build/dev-server.js
- src/router/index.js
Closed [g0v/summit.g0v.tw#6](https://github.com/g0v/summit.g0v.tw/issues/6)
> Scroll to top after page changed

- src/components/AgendumCell.vue
> 議程頁中英互補、以逗號分隔講者名字

- src/components/ParallelAgenda.vue
> 💄 Achieve equal width fo agenda table cell with table-layout: fixed;

- src/components/AgendumCell.vue
- src/components/ParallelAgenda.vue
> Add label for agendum type (keynote/workshop/panel...) and update table font

- src/components/AgendumCell.vue
- src/components/ParallelAgenda.vue
Close https://github.com/g0v/summit.g0v.tw/issues/7
> Only show Track title for first of the consecutive sessions

- src/components/AgendumCell.vue
- src/components/AgendumDialog.vue
> 改短同一軌議程間分隔線，及修復其他樣式bug

- src/App.vue
- src/components/AgendumDialog.vue
- src/pages/AgendaPage.vue
- src/pages/SpeakerPage.vue
- src/router/index.js
> ✨ Extract dialog to <App> so can be invoked by every page

- src/pages/SponsorPage.vue
- src/views/SponsorSection.vue
> 💬 Add sponsor type 'PROMOTING_PARTNER'

- package.json
> 🏗 Add apidoc to build script (forgot in #129)

- README.md
- apidoc.json
- package.json
> Fix build script & edited API doc description

- build/ccip.js
@denny0223 好像是太小的圖片不會有 thumbnail  的樣子，我有其他東西要上，就先直接merg3羅
> fix(ccip): fallback to .url if .thumbnails not available

- src/pages/TransportPage.vue
- src/router/index.js
- src/styles/global.scss
- src/views/HeroImage/HeroImage.vue
- src/views/NavBar.vue
Close part of #116 
cc @hereismglee
> Add /transport page

- src/pages/LandingPage.vue
- src/views/TheFooter.vue
close #141 
Reference:
https://g0v.hackpad.tw/ep/pad/static/2mprMIpYMz9
http://en-us.confcodeofconduct.com/
> 💬 Add the important Code of Conduct

- src/views/NavBar.vue
- src/vue-awesome.js
> 💬 Add register link to NavBar

- src/components/AgendumCell.vue
> 💄 Fix agendum label and track title to top of cell

- src/components/CtaButton.vue
- src/views/HeroImage/HeroImage.vue
> Add slogon and remove link of map in hero image

- src/App.vue
- src/components/AgendumCell.vue
- src/pages/AgendaPage.vue
- src/pages/SpeakerPage.vue
- src/router/index.js
Example: https://summit.g0v.tw/2018/agenda/Oct_7
close #153
> permalink for agenda of certain date

- README.md
- src/pages/AgendaPage.vue
- src/pages/LandingPage.vue
> "bidirectional" interpretation... "Mandarin"; README minor update

- src/components/AgendumCell.vue
- src/components/AgendumDialog.vue
> Hide 'tw' country flag

- package.json
- scripts/pull_airtable.js
- src/components/AgendumCell.vue
- src/components/ParallelAgenda.vue
- src/main.js
- src/pages/AgendaPage.vue
- static/airtable_data/index.js
- yarn.lock
Example: http://localhost:8080/2018/agenda/Oct_6?track=recEbhwt9btwCiox0
> Add query string driven popover for 'TRACK' info

- src/components/AgendumCell.vue
- src/components/AgendumDialog.vue
> 💄 Use country code instead of flag by default

- src/components/AgendumCell.vue
- src/components/AgendumDialog.vue
- src/pages/AgendaPage.vue
- src/pages/SpeakerPage.vue
- static/airtable_data/index.js
~~not closing #142~~ next PR QQ
close #159
> [WIP] moderator related  information

- src/pages/SpeakerPage.vue
close #142 
麻煩 @chiahao 再檢查看看~
> ✨ Sort speakers accroding to locale, unicode and IS_MODERATOR

- src/components/AgendumDialog.vue
> ✨ Show date in AgendumDialog

- src/styles/global.scss
- src/views/NavBar.vue
- src/views/TheFooter.vue
> 💄 Tweak styles

- src/components/CtaButton.vue
- src/pages/LandingPage.vue
- src/views/HeroImage/HeroImage.vue
> Move 'media contact' to CTA button

- src/views/SponsorSection.vue
> 💄lower sponsor icon opacity when hovered/expanded

- src/store/index.js
Thanks @yoyo930021 @denny0223 for the code snippet!
> ✨ Guess user prefer languague by navigator.languague

- src/views/HeroImage/HeroImage.vue
> 💬 update link of Media Contack

- src/components/AgendumCell.vue
- src/components/MainButton.vue
close part of #154, scrolling behavior is not stable on mobile device
> Highlight agenda of active track with darker background color

- src/components/AgendumCell.vue
> Add english version titles in staff page
